config/routes.rb
Quiz1::Application.routes.draw do

  root 'pages#index'

  resources :pages, path: 'movies'

end

app/models/movies.rb
class Movies < ActiveRecord::Base
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@movies = Movies.all
	end

	def new
		@movie = Movies.new
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class= 'title'>
<h1> Welcome to Movie List! </h1>
</div>



<% @movies.each do |movie| %>
  <div>
    <h1><%= movie.name %></h1><br />
    <i><%= movie.year %></i><br />
    <p><%= movie.description %></p><br />
  </div>

  <hr />
<% end %>

<%= new_page_path  'Click here to add your favorite!' %>

app/views/pages/new.html.erb
<h1> Enter Movie Details</h1>
	<%= simple_form_for @movie do |f| %>
	<%= f.input :name %>
	<% end %>
	